POST localhost:8080/category
Content-Type: application/json

{
  "name_uz": "O'zbekistan",
  "name_ru": "ЎЗБЕКИСТОН",
  "name_en": "Uzbekistan",
  "orderNumber": 1,
  "visible": true
}
###
GET localhost:8080/category
###

