POST localhost:8080/profile
Content-Type: application/json

{
  "name": "Diyor",
  "surname": "Saidov",
  "password": "nimaDebOylisan",
  "email": "saidovdiyer777@gmail.com",
  "phone": "+998995191612",
  "role": "MODERATOR",


}
###
GET localhost:8080/profile
