POST localhost:8080/category
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInN1YiI6Iis5OTg5OTAwMjYzODUiLCJpYXQiOjE3MzEyMzk1NjcsImV4cCI6MTczMTMyNTk2N30.IID5KLQr_XJ-7546CROHO-BuU4FxaK6KPprKBo12Ctw

{
  "name_uz": "Jahon",
  "name_ru": "Jahongir",
  "name_en": "Jovoq",
  "orderNumber": 2
}
###
GET localhost:8080/category
###

